// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/esg-dashboard/Alpine.tsx": () => import("../components/mockups/esg-dashboard/Alpine.tsx"),
  "./components/mockups/esg-dashboard/Forest.tsx": () => import("../components/mockups/esg-dashboard/Forest.tsx")
};
